default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lab_4_2023_development
  #port: 5433

test:
  <<: *default
  database: lab_4_2023_test
  #port: 5433

production:
  <<: *default
  database: lab_4_2023_production
  username: lab_4_2023
  password: <%= ENV["BASE_PROJECT_2023_DATABASE_PASSWORD"] %>
