Product.create(product_name: "Paquete de arroz", product_price: 3500)
Product.create(product_name: "Coca Cola", product_price: 1800)
Product.create(product_name: "Lata de atún", product_price: 2000)
Product.create(product_name: "Galletas Oreo", product_price: 2500)
Product.create(product_name: "Paquete de azucar", product_price: 2600)
Product.create(product_name: "Pechuga de pollo", product_price: 4200)
